{"name": "test_landslide_case_start", "status": "failed", "statusDetails": {"message": "AssertionError: landslide is running a case!\nassert False", "trace": "get_test_id = False\n\n    def test_landslide_case_start(get_test_id):\n>       assert get_test_id, \"landslide is running a case!\"\nE       AssertionError: landslide is running a case!\nE       assert False\n\ntest_01.py:49: AssertionError"}, "attachments": [{"name": "log", "source": "e84a17ab-fdcd-47a8-806b-94c06f1a7692-attachment.txt", "type": "text/plain"}], "start": 1566726304016, "stop": 1566726304017, "uuid": "5e759e6a-38cf-4fe5-bb17-b13930784bfd", "historyId": "9eb2b9f80043f88b2f58d008f2727442", "testCaseId": "33ad51ef22b419069fa1764037828b3a", "fullName": "test_01#test_landslide_case_start", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "23246-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}