{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_001_pdu_establishment.py:51: AssertionError"}, "attachments": [{"name": "log", "source": "9bf62e55-cfd8-4f03-9e05-37bd561acc63-attachment.txt", "type": "text/plain"}], "start": 1566877021866, "stop": 1566877021866, "uuid": "19ab7097-0012-494d-a6d3-1944930fac2e", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "ea9e49c52440a3ab13f473cccaa01fbc", "fullName": "test_001_pdu_establishment#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_001_pdu_establishment"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "29919-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_pdu_establishment"}]}